M48
; DRILL file {KiCad (6.0.6)} date Thu Apr  6 13:29:02 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-04-06T13:29:02+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.6)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1772
%
G90
G05
T1
X2.5Y-5.33
X2.51Y-3.69
T2
X2.5Y-2.8
T0
M30
